### ISSUE TITLE
drag and scroll crash

### ISSUE THREAD

**Issue by eboudrant** [askerov/DynamicGrid#36]
When I start dragging an item to the end of the list it scroll the gridview, at one point it crash with : 

```
E/AndroidRuntime(16580): java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference
E/AndroidRuntime(16580):    at android.widget.AdapterView.getPositionForView(AdapterView.java:598)
E/AndroidRuntime(16580):    at org.askerov.dynamicgrid.DynamicGridView.getColumnAndRowForView(DynamicGridView.java:756)
E/AndroidRuntime(16580):    at org.askerov.dynamicgrid.DynamicGridView.handleCellSwitch(DynamicGridView.java:651)
E/AndroidRuntime(16580):    at org.askerov.dynamicgrid.DynamicGridView.onTouchEvent(DynamicGridView.java:431)
E/AndroidRuntime(16580):    at android.view.View.dispatchTouchEvent(View.java:7706)
```

**Comment by vabhatia** [comment]
I am also getting this crash.

**Comment by RegisAG** [comment]
Also this crash. Not often at all but happens.... I don't know in what conditions.
