### ISSUE TITLE
Nullpointer exception while Dragging and Dropping

### ISSUE THREAD

**Issue by sarfarazmadhia** [askerov/DynamicGrid#64]
Please see the Crash Trash. I believe, when adapter.notfydatasetchanged is called and that time when we try to Drag and Down, It causes Crash. As i would like to refresh my views by a asynchronous Task and also allow Dragging and Dropping of items.

03-02 11:48:23.404: E/AndroidRuntime(21485): java.lang.NullPointerException
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.widget.AdapterView.getPositionForView(AdapterView.java:665)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at org.askerov.dynamicgrid.DynamicGridView.getColumnAndRowForView(LibraryGridView.java:935)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at org.askerov.dynamicgrid.DynamicGridView.handleCellSwitch(LibraryGridView.java:721)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at org.askerov.dynamicgrid.DynamicGridView.onTouchEvent(LibraryGridView.java:478)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.View.dispatchTouchEvent(View.java:8135)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2417)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2141)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2423)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2156)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2423)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2156)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2423)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2156)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2423)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2156)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2423)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2156)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2423)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2156)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2423)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2156)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2423)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2156)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2423)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2156)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2423)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2156)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2423)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2156)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2423)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2156)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2295)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1622)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.app.Activity.dispatchTouchEvent(Activity.java:2565)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2243)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.View.dispatchPointerEvent(View.java:8343)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4743)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4609)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4167)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4221)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4190)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4301)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4198)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4358)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4167)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4221)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4190)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4198)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4167)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6517)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6434)
03-02 11:48:23.404: E/AndroidRuntime(21485): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6405

**Comment by Ki41foo** [comment]
I have same issue when dragging last item.

**Comment by JingHaifeng** [comment]
I fixed it and pulled.
