### ISSUE TITLE
android.view.InflateException: Binary XML file line #8: Error inflating class org.askerov.dynamicgrid.DynamicGridView

### ISSUE THREAD

**Issue by RegisAG** [askerov/DynamicGrid#66]
I want to launch the project in Eclipse. I imported the GridActivity project and the dynamicgrid library, added dynamicgrid to the build path of the GridActivity project. But I get the crash here below. Any help would be appreciated ! Thanks.

04-29 11:27:09.591: E/AndroidRuntime(13629): FATAL EXCEPTION: main
04-29 11:27:09.591: E/AndroidRuntime(13629): Process: org.askerov.dynamicgrid.example, PID: 13629
04-29 11:27:09.591: E/AndroidRuntime(13629): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.askerov.dynamicgrid.example/org.askerov.dynamicgrid.example.GridActivity}: android.view.InflateException: Binary XML file line #8: Error inflating class org.askerov.dynamicgrid.DynamicGridView
04-29 11:27:09.591: E/AndroidRuntime(13629): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2693)
04-29 11:27:09.591: E/AndroidRuntime(13629): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2760)
04-29 11:27:09.591: E/AndroidRuntime(13629): 	at android.app.ActivityThread.access$900(ActivityThread.java:177)
04-29 11:27:09.591: E/AndroidRuntime(13629): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
04-29 11:27:09.591: E/AndroidRuntime(13629): 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-29 11:27:09.591: E/AndroidRuntime(13629): 	at android.os.Looper.loop(Looper.java:145)
04-29 11:27:09.591: E/AndroidRuntime(13629): 	at android.app.ActivityThread.main(ActivityThread.java:5944)
04-29 11:27:09.591: E/AndroidRuntime(13629): 	at java.lang.reflect.Method.invoke(Native Method)
04-29 11:27:09.591: E/AndroidRuntime(13629): 	at java.lang.reflect.Method.invoke(Method.java:372)
04-29 11:27:09.591: E/AndroidRuntime(13629): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1389)
04-29 11:27:09.591: E/AndroidRuntime(13629): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1184)
04-29 11:27:09.591: E/AndroidRuntime(13629): Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class org.askerov.dynamicgrid.DynamicGridView
04-29 11:27:09.591: E/AndroidRuntime(13629): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
04-29 11:27:09.591: E/AndroidRuntime(13629): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
04-29 11:27:09.591: E/AndroidRuntime(13629): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
04-29 11:27:09.591: E/AndroidRuntime(13629): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
04-29 11:27:09.591: E/AndroidRuntime(13629): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
04-29 11:27:09.591: E/AndroidRuntime(13629): 	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:435)
04-29 11:27:09.591: E/AndroidRuntime(13629): 	at android.app.Activity.setContentView(Activity.java:2267)
04-29 11:27:09.591: E/AndroidRuntime(13629): 	at org.askerov.dynamicgrid.example.GridActivity.onCreate(GridActivity.java:23)
04-29 11:27:09.591: E/AndroidRuntime(13629): 	at android.app.Activity.performCreate(Activity.java:6289)
04-29 11:27:09.591: E/AndroidRuntime(13629): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
04-29 11:27:09.591: E/AndroidRuntime(13629): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
04-29 11:27:09.591: E/AndroidRuntime(13629): 	... 10 more
04-29 11:27:09.591: E/AndroidRuntime(13629): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.askerov.dynamicgrid.DynamicGridView" on path: DexPathList[[zip file "/data/app/org.askerov.dynamicgrid.example-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
04-29 11:27:09.591: E/AndroidRuntime(13629): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-29 11:27:09.591: E/AndroidRuntime(13629): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
04-29 11:27:09.591: E/AndroidRuntime(13629): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
04-29 11:27:09.591: E/AndroidRuntime(13629): 	at android.view.LayoutInflater.createView(LayoutInflater.java:578)
04-29 11:27:09.591: E/AndroidRuntime(13629): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
04-29 11:27:09.591: E/AndroidRuntime(13629): 	... 20 more
04-29 11:27:09.591: E/AndroidRuntime(13629): 	Suppressed: java.lang.ClassNotFoundException: org.askerov.dynamicgrid.DynamicGridView
04-29 11:27:09.591: E/AndroidRuntime(13629): 		at java.lang.Class.classForName(Native Method)
04-29 11:27:09.591: E/AndroidRuntime(13629): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
04-29 11:27:09.591: E/AndroidRuntime(13629): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
04-29 11:27:09.591: E/AndroidRuntime(13629): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
04-29 11:27:09.591: E/AndroidRuntime(13629): 		... 23 more
04-29 11:27:09.591: E/AndroidRuntime(13629): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by omidaminiva** [comment]
In manifest android:minSdkVersion="8" change to  higher number. I changed it to 15 and it started working. It could be because my application's minSdkVersion is 15.

**Comment by 159159951** [comment]
I got this proplem with you,
In my case, I put class is not consisten with XML strucs layout file
I change to (only in my project)
 <com.org.askerov.dynamicgrid.DynamicGridView
